# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.0
    Contact: skycoin.doe@example.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_200_2_version import InlineResponse2002Version  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2002Version(unittest.TestCase):
    """InlineResponse2002Version unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002Version(self):
        """Test InlineResponse2002Version"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_200_2_version.InlineResponse2002Version()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
