# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.0
    Contact: skycoin.doe@example.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wallet_entry import WalletEntry  # noqa: E501
from swagger_client.rest import ApiException


class TestWalletEntry(unittest.TestCase):
    """WalletEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletEntry(self):
        """Test WalletEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wallet_entry.WalletEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
