/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Apiv1walletsEntries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Apiv1walletsEntriesTests
    {
        // TODO uncomment below to declare an instance variable for Apiv1walletsEntries
        //private Apiv1walletsEntries instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Apiv1walletsEntries
            //instance = new Apiv1walletsEntries();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Apiv1walletsEntries
        /// </summary>
        [Test]
        public void Apiv1walletsEntriesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Apiv1walletsEntries
            //Assert.IsInstanceOfType<Apiv1walletsEntries> (instance, "variable 'instance' is a Apiv1walletsEntries");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PublicKey'
        /// </summary>
        [Test]
        public void PublicKeyTest()
        {
            // TODO unit test for the property 'PublicKey'
        }

    }

}
