/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2003
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2003Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2003
        //private InlineResponse2003 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2003
            //instance = new InlineResponse2003();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2003
        /// </summary>
        [Test]
        public void InlineResponse2003InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2003
            //Assert.IsInstanceOfType<InlineResponse2003> (instance, "variable 'instance' is a InlineResponse2003");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'ConnectedAt'
        /// </summary>
        [Test]
        public void ConnectedAtTest()
        {
            // TODO unit test for the property 'ConnectedAt'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsTrustedPeer'
        /// </summary>
        [Test]
        public void IsTrustedPeerTest()
        {
            // TODO unit test for the property 'IsTrustedPeer'
        }
        /// <summary>
        /// Test the property 'LastReceived'
        /// </summary>
        [Test]
        public void LastReceivedTest()
        {
            // TODO unit test for the property 'LastReceived'
        }
        /// <summary>
        /// Test the property 'LastSent'
        /// </summary>
        [Test]
        public void LastSentTest()
        {
            // TODO unit test for the property 'LastSent'
        }
        /// <summary>
        /// Test the property 'ListenPort'
        /// </summary>
        [Test]
        public void ListenPortTest()
        {
            // TODO unit test for the property 'ListenPort'
        }
        /// <summary>
        /// Test the property 'Mirror'
        /// </summary>
        [Test]
        public void MirrorTest()
        {
            // TODO unit test for the property 'Mirror'
        }
        /// <summary>
        /// Test the property 'Outgoing'
        /// </summary>
        [Test]
        public void OutgoingTest()
        {
            // TODO unit test for the property 'Outgoing'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'UnconfirmedVerifyTransaction'
        /// </summary>
        [Test]
        public void UnconfirmedVerifyTransactionTest()
        {
            // TODO unit test for the property 'UnconfirmedVerifyTransaction'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Test]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }

    }

}
