/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2002
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2002Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2002
        //private InlineResponse2002 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2002
            //instance = new InlineResponse2002();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2002
        /// </summary>
        [Test]
        public void InlineResponse2002InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2002
            //Assert.IsInstanceOfType<InlineResponse2002> (instance, "variable 'instance' is a InlineResponse2002");
        }


        /// <summary>
        /// Test the property 'Blockchain'
        /// </summary>
        [Test]
        public void BlockchainTest()
        {
            // TODO unit test for the property 'Blockchain'
        }
        /// <summary>
        /// Test the property 'Coin'
        /// </summary>
        [Test]
        public void CoinTest()
        {
            // TODO unit test for the property 'Coin'
        }
        /// <summary>
        /// Test the property 'CspEnabled'
        /// </summary>
        [Test]
        public void CspEnabledTest()
        {
            // TODO unit test for the property 'CspEnabled'
        }
        /// <summary>
        /// Test the property 'CsrfEnabled'
        /// </summary>
        [Test]
        public void CsrfEnabledTest()
        {
            // TODO unit test for the property 'CsrfEnabled'
        }
        /// <summary>
        /// Test the property 'GuiEnabled'
        /// </summary>
        [Test]
        public void GuiEnabledTest()
        {
            // TODO unit test for the property 'GuiEnabled'
        }
        /// <summary>
        /// Test the property 'IncomingConnections'
        /// </summary>
        [Test]
        public void IncomingConnectionsTest()
        {
            // TODO unit test for the property 'IncomingConnections'
        }
        /// <summary>
        /// Test the property 'JsonRpcEnabled'
        /// </summary>
        [Test]
        public void JsonRpcEnabledTest()
        {
            // TODO unit test for the property 'JsonRpcEnabled'
        }
        /// <summary>
        /// Test the property 'OpenConnections'
        /// </summary>
        [Test]
        public void OpenConnectionsTest()
        {
            // TODO unit test for the property 'OpenConnections'
        }
        /// <summary>
        /// Test the property 'OutgoingConnections'
        /// </summary>
        [Test]
        public void OutgoingConnectionsTest()
        {
            // TODO unit test for the property 'OutgoingConnections'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Test]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'UnconfirmedVerifyTransaction'
        /// </summary>
        [Test]
        public void UnconfirmedVerifyTransactionTest()
        {
            // TODO unit test for the property 'UnconfirmedVerifyTransaction'
        }
        /// <summary>
        /// Test the property 'UnversionedApiEnabled'
        /// </summary>
        [Test]
        public void UnversionedApiEnabledTest()
        {
            // TODO unit test for the property 'UnversionedApiEnabled'
        }
        /// <summary>
        /// Test the property 'Uptime'
        /// </summary>
        [Test]
        public void UptimeTest()
        {
            // TODO unit test for the property 'Uptime'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Test]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'UserVerifyTransaction'
        /// </summary>
        [Test]
        public void UserVerifyTransactionTest()
        {
            // TODO unit test for the property 'UserVerifyTransaction'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'WalletApiEnabled'
        /// </summary>
        [Test]
        public void WalletApiEnabledTest()
        {
            // TODO unit test for the property 'WalletApiEnabled'
        }

    }

}
