/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2005
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2005Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2005
        //private InlineResponse2005 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2005
            //instance = new InlineResponse2005();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2005
        /// </summary>
        [Test]
        public void InlineResponse2005InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2005
            //Assert.IsInstanceOfType<InlineResponse2005> (instance, "variable 'instance' is a InlineResponse2005");
        }


        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Test]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }

    }

}
