/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2002UnconfirmedVerifyTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2002UnconfirmedVerifyTransactionTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2002UnconfirmedVerifyTransaction
        //private InlineResponse2002UnconfirmedVerifyTransaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2002UnconfirmedVerifyTransaction
            //instance = new InlineResponse2002UnconfirmedVerifyTransaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2002UnconfirmedVerifyTransaction
        /// </summary>
        [Test]
        public void InlineResponse2002UnconfirmedVerifyTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2002UnconfirmedVerifyTransaction
            //Assert.IsInstanceOfType<InlineResponse2002UnconfirmedVerifyTransaction> (instance, "variable 'instance' is a InlineResponse2002UnconfirmedVerifyTransaction");
        }


        /// <summary>
        /// Test the property 'BurnFactor'
        /// </summary>
        [Test]
        public void BurnFactorTest()
        {
            // TODO unit test for the property 'BurnFactor'
        }
        /// <summary>
        /// Test the property 'MaxDecimal'
        /// </summary>
        [Test]
        public void MaxDecimalTest()
        {
            // TODO unit test for the property 'MaxDecimal'
        }
        /// <summary>
        /// Test the property 'MaxTransactionSize'
        /// </summary>
        [Test]
        public void MaxTransactionSizeTest()
        {
            // TODO unit test for the property 'MaxTransactionSize'
        }

    }

}
