/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2002Blockchain
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2002BlockchainTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2002Blockchain
        //private InlineResponse2002Blockchain instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2002Blockchain
            //instance = new InlineResponse2002Blockchain();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2002Blockchain
        /// </summary>
        [Test]
        public void InlineResponse2002BlockchainInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2002Blockchain
            //Assert.IsInstanceOfType<InlineResponse2002Blockchain> (instance, "variable 'instance' is a InlineResponse2002Blockchain");
        }


        /// <summary>
        /// Test the property 'Head'
        /// </summary>
        [Test]
        public void HeadTest()
        {
            // TODO unit test for the property 'Head'
        }
        /// <summary>
        /// Test the property 'TimeSinceLastBlock'
        /// </summary>
        [Test]
        public void TimeSinceLastBlockTest()
        {
            // TODO unit test for the property 'TimeSinceLastBlock'
        }
        /// <summary>
        /// Test the property 'Unconfirmed'
        /// </summary>
        [Test]
        public void UnconfirmedTest()
        {
            // TODO unit test for the property 'Unconfirmed'
        }
        /// <summary>
        /// Test the property 'Unspents'
        /// </summary>
        [Test]
        public void UnspentsTest()
        {
            // TODO unit test for the property 'Unspents'
        }

    }

}
