/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WalletMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WalletMetaTests
    {
        // TODO uncomment below to declare an instance variable for WalletMeta
        //private WalletMeta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WalletMeta
            //instance = new WalletMeta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WalletMeta
        /// </summary>
        [Test]
        public void WalletMetaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WalletMeta
            //Assert.IsInstanceOfType<WalletMeta> (instance, "variable 'instance' is a WalletMeta");
        }


        /// <summary>
        /// Test the property 'Coin'
        /// </summary>
        [Test]
        public void CoinTest()
        {
            // TODO unit test for the property 'Coin'
        }
        /// <summary>
        /// Test the property 'CryptoType'
        /// </summary>
        [Test]
        public void CryptoTypeTest()
        {
            // TODO unit test for the property 'CryptoType'
        }
        /// <summary>
        /// Test the property 'Encrypted'
        /// </summary>
        [Test]
        public void EncryptedTest()
        {
            // TODO unit test for the property 'Encrypted'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
