/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse2002Blockchain
    /// </summary>
    [DataContract]
    public partial class InlineResponse2002Blockchain :  IEquatable<InlineResponse2002Blockchain>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2002Blockchain" /> class.
        /// </summary>
        /// <param name="Head">Head.</param>
        /// <param name="TimeSinceLastBlock">TimeSinceLastBlock.</param>
        /// <param name="Unconfirmed">Unconfirmed.</param>
        /// <param name="Unspents">Unspents.</param>
        public InlineResponse2002Blockchain(InlineResponse2002BlockchainHead Head = default(InlineResponse2002BlockchainHead), string TimeSinceLastBlock = default(string), long? Unconfirmed = default(long?), long? Unspents = default(long?))
        {
            this.Head = Head;
            this.TimeSinceLastBlock = TimeSinceLastBlock;
            this.Unconfirmed = Unconfirmed;
            this.Unspents = Unspents;
        }
        
        /// <summary>
        /// Gets or Sets Head
        /// </summary>
        [DataMember(Name="head", EmitDefaultValue=false)]
        public InlineResponse2002BlockchainHead Head { get; set; }

        /// <summary>
        /// Gets or Sets TimeSinceLastBlock
        /// </summary>
        [DataMember(Name="time_since_last_block", EmitDefaultValue=false)]
        public string TimeSinceLastBlock { get; set; }

        /// <summary>
        /// Gets or Sets Unconfirmed
        /// </summary>
        [DataMember(Name="unconfirmed", EmitDefaultValue=false)]
        public long? Unconfirmed { get; set; }

        /// <summary>
        /// Gets or Sets Unspents
        /// </summary>
        [DataMember(Name="unspents", EmitDefaultValue=false)]
        public long? Unspents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2002Blockchain {\n");
            sb.Append("  Head: ").Append(Head).Append("\n");
            sb.Append("  TimeSinceLastBlock: ").Append(TimeSinceLastBlock).Append("\n");
            sb.Append("  Unconfirmed: ").Append(Unconfirmed).Append("\n");
            sb.Append("  Unspents: ").Append(Unspents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2002Blockchain);
        }

        /// <summary>
        /// Returns true if InlineResponse2002Blockchain instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2002Blockchain to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2002Blockchain input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Head == input.Head ||
                    (this.Head != null &&
                    this.Head.Equals(input.Head))
                ) && 
                (
                    this.TimeSinceLastBlock == input.TimeSinceLastBlock ||
                    (this.TimeSinceLastBlock != null &&
                    this.TimeSinceLastBlock.Equals(input.TimeSinceLastBlock))
                ) && 
                (
                    this.Unconfirmed == input.Unconfirmed ||
                    (this.Unconfirmed != null &&
                    this.Unconfirmed.Equals(input.Unconfirmed))
                ) && 
                (
                    this.Unspents == input.Unspents ||
                    (this.Unspents != null &&
                    this.Unspents.Equals(input.Unspents))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Head != null)
                    hashCode = hashCode * 59 + this.Head.GetHashCode();
                if (this.TimeSinceLastBlock != null)
                    hashCode = hashCode * 59 + this.TimeSinceLastBlock.GetHashCode();
                if (this.Unconfirmed != null)
                    hashCode = hashCode * 59 + this.Unconfirmed.GetHashCode();
                if (this.Unspents != null)
                    hashCode = hashCode * 59 + this.Unspents.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
