/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse2002BlockchainHead
    /// </summary>
    [DataContract]
    public partial class InlineResponse2002BlockchainHead :  IEquatable<InlineResponse2002BlockchainHead>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2002BlockchainHead" /> class.
        /// </summary>
        /// <param name="BlockHash">BlockHash.</param>
        /// <param name="Fee">Fee.</param>
        /// <param name="PreviousBlockHash">PreviousBlockHash.</param>
        /// <param name="Seq">Seq.</param>
        /// <param name="Timestamp">Timestamp.</param>
        /// <param name="TxBodyHash">TxBodyHash.</param>
        /// <param name="UxHash">UxHash.</param>
        /// <param name="Version">Version.</param>
        public InlineResponse2002BlockchainHead(string BlockHash = default(string), long? Fee = default(long?), string PreviousBlockHash = default(string), string Seq = default(string), long? Timestamp = default(long?), string TxBodyHash = default(string), string UxHash = default(string), long? Version = default(long?))
        {
            this.BlockHash = BlockHash;
            this.Fee = Fee;
            this.PreviousBlockHash = PreviousBlockHash;
            this.Seq = Seq;
            this.Timestamp = Timestamp;
            this.TxBodyHash = TxBodyHash;
            this.UxHash = UxHash;
            this.Version = Version;
        }
        
        /// <summary>
        /// Gets or Sets BlockHash
        /// </summary>
        [DataMember(Name="block_hash", EmitDefaultValue=false)]
        public string BlockHash { get; set; }

        /// <summary>
        /// Gets or Sets Fee
        /// </summary>
        [DataMember(Name="fee", EmitDefaultValue=false)]
        public long? Fee { get; set; }

        /// <summary>
        /// Gets or Sets PreviousBlockHash
        /// </summary>
        [DataMember(Name="previous_block_hash", EmitDefaultValue=false)]
        public string PreviousBlockHash { get; set; }

        /// <summary>
        /// Gets or Sets Seq
        /// </summary>
        [DataMember(Name="seq", EmitDefaultValue=false)]
        public string Seq { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public long? Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets TxBodyHash
        /// </summary>
        [DataMember(Name="tx_body_hash", EmitDefaultValue=false)]
        public string TxBodyHash { get; set; }

        /// <summary>
        /// Gets or Sets UxHash
        /// </summary>
        [DataMember(Name="ux_hash", EmitDefaultValue=false)]
        public string UxHash { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public long? Version { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2002BlockchainHead {\n");
            sb.Append("  BlockHash: ").Append(BlockHash).Append("\n");
            sb.Append("  Fee: ").Append(Fee).Append("\n");
            sb.Append("  PreviousBlockHash: ").Append(PreviousBlockHash).Append("\n");
            sb.Append("  Seq: ").Append(Seq).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  TxBodyHash: ").Append(TxBodyHash).Append("\n");
            sb.Append("  UxHash: ").Append(UxHash).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2002BlockchainHead);
        }

        /// <summary>
        /// Returns true if InlineResponse2002BlockchainHead instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2002BlockchainHead to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2002BlockchainHead input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BlockHash == input.BlockHash ||
                    (this.BlockHash != null &&
                    this.BlockHash.Equals(input.BlockHash))
                ) && 
                (
                    this.Fee == input.Fee ||
                    (this.Fee != null &&
                    this.Fee.Equals(input.Fee))
                ) && 
                (
                    this.PreviousBlockHash == input.PreviousBlockHash ||
                    (this.PreviousBlockHash != null &&
                    this.PreviousBlockHash.Equals(input.PreviousBlockHash))
                ) && 
                (
                    this.Seq == input.Seq ||
                    (this.Seq != null &&
                    this.Seq.Equals(input.Seq))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.TxBodyHash == input.TxBodyHash ||
                    (this.TxBodyHash != null &&
                    this.TxBodyHash.Equals(input.TxBodyHash))
                ) && 
                (
                    this.UxHash == input.UxHash ||
                    (this.UxHash != null &&
                    this.UxHash.Equals(input.UxHash))
                ) && 
                (
                    this.Version == input.Version ||
                    (this.Version != null &&
                    this.Version.Equals(input.Version))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BlockHash != null)
                    hashCode = hashCode * 59 + this.BlockHash.GetHashCode();
                if (this.Fee != null)
                    hashCode = hashCode * 59 + this.Fee.GetHashCode();
                if (this.PreviousBlockHash != null)
                    hashCode = hashCode * 59 + this.PreviousBlockHash.GetHashCode();
                if (this.Seq != null)
                    hashCode = hashCode * 59 + this.Seq.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.TxBodyHash != null)
                    hashCode = hashCode * 59 + this.TxBodyHash.GetHashCode();
                if (this.UxHash != null)
                    hashCode = hashCode * 59 + this.UxHash.GetHashCode();
                if (this.Version != null)
                    hashCode = hashCode * 59 + this.Version.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
