=begin
#Skycoin REST API.

#Skycoin is a next-generation cryptocurrency.

OpenAPI spec version: 0.25.0
Contact: skycoin.doe@example.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InlineResponse2002UnconfirmedVerifyTransaction
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse2002UnconfirmedVerifyTransaction' do
  before do
    # run before each test
    @instance = SwaggerClient::InlineResponse2002UnconfirmedVerifyTransaction.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2002UnconfirmedVerifyTransaction' do
    it 'should create an instance of InlineResponse2002UnconfirmedVerifyTransaction' do
      expect(@instance).to be_instance_of(SwaggerClient::InlineResponse2002UnconfirmedVerifyTransaction)
    end
  end
  describe 'test attribute "burn_factor"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max_decimal"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max_transaction_size"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

