# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.0
    Contact: skycoin.doe@example.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.apiv1wallets_entries import Apiv1walletsEntries  # noqa: F401,E501
from swagger_client.models.apiv1wallets_meta import Apiv1walletsMeta  # noqa: F401,E501


class InlineResponse2007(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entries': 'list[Apiv1walletsEntries]',
        'meta': 'Apiv1walletsMeta'
    }

    attribute_map = {
        'entries': 'entries',
        'meta': 'meta'
    }

    def __init__(self, entries=None, meta=None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger"""  # noqa: E501

        self._entries = None
        self._meta = None
        self.discriminator = None

        if entries is not None:
            self.entries = entries
        if meta is not None:
            self.meta = meta

    @property
    def entries(self):
        """Gets the entries of this InlineResponse2007.  # noqa: E501


        :return: The entries of this InlineResponse2007.  # noqa: E501
        :rtype: list[Apiv1walletsEntries]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this InlineResponse2007.


        :param entries: The entries of this InlineResponse2007.  # noqa: E501
        :type: list[Apiv1walletsEntries]
        """

        self._entries = entries

    @property
    def meta(self):
        """Gets the meta of this InlineResponse2007.  # noqa: E501


        :return: The meta of this InlineResponse2007.  # noqa: E501
        :rtype: Apiv1walletsMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this InlineResponse2007.


        :param meta: The meta of this InlineResponse2007.  # noqa: E501
        :type: Apiv1walletsMeta
        """

        self._meta = meta

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2007):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
