# coding: utf-8

"""
    Skycoin REST API.

    Skycoin is a next-generation cryptocurrency.  # noqa: E501

    OpenAPI spec version: 0.25.0
    Contact: skycoin.doe@example.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.inline_response2002_blockchain_head import InlineResponse2002BlockchainHead  # noqa: F401,E501


class InlineResponse2002Blockchain(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'head': 'InlineResponse2002BlockchainHead',
        'time_since_last_block': 'str',
        'unconfirmed': 'int',
        'unspents': 'int'
    }

    attribute_map = {
        'head': 'head',
        'time_since_last_block': 'time_since_last_block',
        'unconfirmed': 'unconfirmed',
        'unspents': 'unspents'
    }

    def __init__(self, head=None, time_since_last_block=None, unconfirmed=None, unspents=None):  # noqa: E501
        """InlineResponse2002Blockchain - a model defined in Swagger"""  # noqa: E501

        self._head = None
        self._time_since_last_block = None
        self._unconfirmed = None
        self._unspents = None
        self.discriminator = None

        if head is not None:
            self.head = head
        if time_since_last_block is not None:
            self.time_since_last_block = time_since_last_block
        if unconfirmed is not None:
            self.unconfirmed = unconfirmed
        if unspents is not None:
            self.unspents = unspents

    @property
    def head(self):
        """Gets the head of this InlineResponse2002Blockchain.  # noqa: E501


        :return: The head of this InlineResponse2002Blockchain.  # noqa: E501
        :rtype: InlineResponse2002BlockchainHead
        """
        return self._head

    @head.setter
    def head(self, head):
        """Sets the head of this InlineResponse2002Blockchain.


        :param head: The head of this InlineResponse2002Blockchain.  # noqa: E501
        :type: InlineResponse2002BlockchainHead
        """

        self._head = head

    @property
    def time_since_last_block(self):
        """Gets the time_since_last_block of this InlineResponse2002Blockchain.  # noqa: E501


        :return: The time_since_last_block of this InlineResponse2002Blockchain.  # noqa: E501
        :rtype: str
        """
        return self._time_since_last_block

    @time_since_last_block.setter
    def time_since_last_block(self, time_since_last_block):
        """Sets the time_since_last_block of this InlineResponse2002Blockchain.


        :param time_since_last_block: The time_since_last_block of this InlineResponse2002Blockchain.  # noqa: E501
        :type: str
        """

        self._time_since_last_block = time_since_last_block

    @property
    def unconfirmed(self):
        """Gets the unconfirmed of this InlineResponse2002Blockchain.  # noqa: E501


        :return: The unconfirmed of this InlineResponse2002Blockchain.  # noqa: E501
        :rtype: int
        """
        return self._unconfirmed

    @unconfirmed.setter
    def unconfirmed(self, unconfirmed):
        """Sets the unconfirmed of this InlineResponse2002Blockchain.


        :param unconfirmed: The unconfirmed of this InlineResponse2002Blockchain.  # noqa: E501
        :type: int
        """

        self._unconfirmed = unconfirmed

    @property
    def unspents(self):
        """Gets the unspents of this InlineResponse2002Blockchain.  # noqa: E501


        :return: The unspents of this InlineResponse2002Blockchain.  # noqa: E501
        :rtype: int
        """
        return self._unspents

    @unspents.setter
    def unspents(self, unspents):
        """Sets the unspents of this InlineResponse2002Blockchain.


        :param unspents: The unspents of this InlineResponse2002Blockchain.  # noqa: E501
        :type: int
        """

        self._unspents = unspents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002Blockchain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
